### ISSUE TITLE
Hostname property for SEO URL conversions?

### ISSUE THREAD

**Issue by AndreasGalster** [PolymerElements/iron-page-url#11]
I'm actually not sure if this is correct practice but for SEO purposes it's considered best practice to define absolute paths vs relative paths. This could be easily solved by data-binding to a hostname property in the iron-page-url element. Though I'm not sure if Google's crawler or crawlers in general can pick up that hostname defined this way. Either way, a hostname property might make sense?

**Comment by rictic** [comment]
Without commenting for or against this SEO theory, I don't think generating URLs with the current scheme and hostname baked in is what's desired. The idea behind this SEO theory is that you want a canonical scheme and hostname in all of your links to encourage crawlers to canonicalize your URLs properly. There should be no difference between the urls `/{{relativeUrl}}` and `{{currentScheme}}://{{currentHostname}}/{{relativeUrl}}`.
